version: "3.1"

services:
  product-service:
    build: .
    container_name: product-service
    env_file:
     - ./.env
    ports:
      - "$WEBSERVER_PORT:$WEBSERVER_PORT"

networks:
  default:
    external:
      name: ansrnetwork